title: "Naty Ova"
description: "Официальный сайт: тексты песен, видео и ссылки на стриминги"
url: "" # например: https://username.github.io
baseurl: "" # если проект-страница, укажите /repo-name

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

exclude:
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js

collections:
  songs:
    output: true
    permalink: /songs/:path/

defaults:
  - scope:
      path: ""
      type: "songs"
    values:
      layout: song
      toc: false

# Навбар/соцсети артиста
artist:
  youtube: "https://youtube.com/@yourchannel"
  spotify: "https://open.spotify.com/artist/XXXXXXXX"
  apple_music: "https://music.apple.com/artist/XXXXXXXX"
  vk_music: "https://vk.com/audios-XXXXXXXX"
  instagram: "https://instagram.com/yourprofile"
  tiktok: "https://www.tiktok.com/@yourprofile"
